# Generated by Django 5.0.1 on 2024-01-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.BinaryField(),
        ),
    ]
