# Generated by Django 5.0.2 on 2024-02-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_postmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
